adjust pre-full workflow

diff --git a/.github/actions/e2e-setup/action.yml b/.github/actions/e2e-setup/action.yml
--- a/.github/actions/e2e-setup/action.yml
+++ b/.github/actions/e2e-setup/action.yml
@@ -20,7 +20,7 @@ runs:
       shell: bash
       run: |
         echo "Pulling wfchain image..."
-        docker pull ghcr.io/cosmos/wfchain:mariuszzak-ift || echo "Failed to pull wfchain image"
+        docker pull ghcr.io/cosmos/wfchain:latest || echo "Failed to pull wfchain image"
 
     - name: Set up foundry tooling
       uses: ./.github/actions/foundry-setup
