ci: updated ci

diff --git a/.github/workflows/abigen.yaml b/.github/workflows/abigen.yaml
--- a/.github/workflows/abigen.yaml
+++ b/.github/workflows/abigen.yaml
@@ -16,7 +16,7 @@ on:
       - 'packages/go-abigen/**'
 
 jobs:
-  abigen-check:
+  check:
     runs-on: depot-ubuntu-22.04-4
     steps:
       - uses: actions/checkout@v4
@@ -32,12 +32,19 @@ jobs:
       - name: Install abigen
         run: go install github.com/ethereum/go-ethereum/cmd/abigen@latest
 
-      - name: Check that generating files from go does not create any changes
-        uses: nickcharlton/diff-check@main
-        with: 
-          command: just generate-abi
+      - name: Run abigen
+        run: just generate-abi
 
-  abigen-golangci:
+      - name: Check for diffs in go-abigen
+        run: |
+          if ! git diff --quiet HEAD -- packages/go-abigen; then
+            echo "Git diff found in the selected directory. Failing the job."
+            exit 1
+          else
+            echo "No changes detected in the selected directory."
+          fi
+
+  golangci:
     runs-on: depot-ubuntu-22.04-4
     steps:
       - uses: actions/checkout@v4
@@ -52,7 +59,7 @@ jobs:
           version: v1.63
           working-directory: packages/go-abigen
 
-  abigen-test:
+  test:
     runs-on: depot-ubuntu-22.04-4
     steps:
       - uses: actions/checkout@v4
